### ISSUE TITLE
+event update and list hang when event has no name

### ISSUE THREAD

**Issue by jespirit** [pyrox18/SchedulerBot#13]
I tried creating an event and then updating the event to start at a later time, except I didn't include the name for the event. The event is updated with the new time (I checked PostgreSQL database) but the "Updated event." and the yellow event information box doesn't show up. It seems that SchedulerBot just hangs. The same thing happens when I run the `+event list 1` command to display the event details and again SchedulerBot hangs.

Steps to recreate:

1. `+event dummy1 today at 10:00pm`
2. `+event update 1 today at 10:30pm` (SchedulerBot hangs here)
3. `+event list 1` (SchedulerBot hangs again here)

It seems as if I was able to fix it by testing to check if the event name was null or empty before adding a field to the `DiscordEmbedBuilder` in `EventEmbedFactory.cs` file.

```cs
embed.AddField("Event Name", string.IsNullOrEmpty(evt.Name) ? "N/A" : evt.Name);
```

![event-update-hangs](https://user-images.githubusercontent.com/5477929/46901007-99b5e700-ce79-11e8-890c-d1f44f811c87.gif)

**Comment by pyrox18** [comment]
Sorry for the late response; I wasn't getting any notifications from GitHub via email, so I didn't notice you made these issues.

The way that the event parser works now is that it requires a name and date/time component to update either part of the event. The fix you implemented makes it so that the event embed builder handles a null event name properly, but the event name disappearing shouldn't happen to begin with. Can you rework the event parser to be able to update the event name and event date/time independently of each other?

Perhaps something like:
- If there is an event name but no date/time in the body (which can be detected by checking if `results.Count == 0` after calling `DateTimeRecognizer.RecognizeDateTime`), then just update the event name and leave the date/time as is.
- If there is an event date/time but no event name (which can be detected by checking if the string returned by `RemoveCaseInsensitive` is null or empty, then just update the event date/time and leave the name as is.

Also, this should only apply to event updates. Event creations must have both names and date/times, so you might need to tweak the code for these situations to be handled separately (currently they both use the same methods to parse the message body).

I'm going to leave your PR open for now until you can implement this functionality.
